name: ForcedGrammar
version: 1.3.1
description: Edits chat messages to correct basic grammatical and spelling errors.
author: ReddChicken (liam@reddchicken.net)
main: net.reddchicken.ForcedGrammar.ForcedGrammar